openapi: 3.0.0
info:
  title: Toodle API
  version: 1.0.0
  description: A simple API for managing tasks
servers:
  - url: http://localhost:3000
paths: {}

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Task:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        description:
          type: string
        priority:
          type: integer
        dueDate:
          type: string
          format: date-time
        completed:
          type: boolean
        dateCreated:
          type: string
          format: date-time
