openapi: 3.0.0
info:
  title: Toodle API
  version: 1.0.0
  description: A simple API for managing tasks
servers:
  - url: http://localhost:3000

paths:
  /tasks:
    get:
      summary: Get all tasks
      responses:
        "200":
          description: A list of tasks
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Task"

  /tasks/{id}:
    get:
      summary: Get a task by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: ID of the task to retrieve
      responses:
        "200":
          description: Task found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Task"
        "404":
          description: Task not found

    post:
      summary: Create a new task
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Task"
      responses:
        "201":
          description: Task created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Task"

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Task:
      type: object
      properties:
        id:
          type: integer
          example: 1
        title:
          type: string
          example: "Wash the car"
        description:
          type: string
          example: "I drove through a muddy puddle"
        priority:
          type: integer
          example: 2
        dueDate:
          type: string
          format: date-time
          example: "2025-07-01T14:30:00Z"
        completed:
          type: boolean
          example: false
        dateCreated:
          type: string
          format: date-time
