openapi: 3.0.0
info:
  title: Toodle API
  version: 1.0.0
  description: A simple API for managing tasks
servers:
  - url: http://localhost:3000

paths:
  /tasks:
    get:
      summary: Get all tasks
      responses:
        "200":
          description: A list of tasks
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Task"

  /tasks/{id}:
    get:
      summary: Get a task by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: ID of the task to retrieve
      responses:
        "200":
          description: Task found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Task"
        "404":
          description: Task not found

    post:
      summary: Create a new task
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Task"
      responses:
        "201":
          description: Task created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Task"

    put:
      summary: Update a task by ID
      tags:
        - Tasks
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: The ID of the task to update
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  example: "Updated Task Title"
                description:
                  type: string
                  example: "Updated task description"
                priority:
                  type: integer
                  example: 1
                dueDate:
                  type: string
                  format: date-time
                  example: "2026-03-15T00:00:00Z"
                completed:
                  type: boolean
                  example: true
      responses:
        "200":
          description: Task updated successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Task"
        "400":
          description: Bad request
        "404":
          description: Task not found

    delete:
      summary: Delete a task by ID
      tags:
        - Tasks
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: The ID of the task to delete
      responses:
        "204":
          description: Task successfully deleted (no content)
        "404":
          description: Task not found
        "400":
          description: Invalid task ID
      security:
        - bearerAuth: []

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Task:
      type: object
      properties:
        id:
          type: integer
          example: 1
        title:
          type: string
          example: "Wash the car"
        description:
          type: string
          example: "I drove through a muddy puddle"
        priority:
          type: integer
          example: 2
        dueDate:
          type: string
          format: date-time
          example: "2025-07-01T14:30:00Z"
        completed:
          type: boolean
          example: false
        dateCreated:
          type: string
          format: date-time
